#!/bin/bash

app_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$app_dir/functions" ]]; then
  source "$app_dir/functions"
fi

config_dir="$app_dir/../hosting/config/containers"

if [[ "$1" == "app:ai:logs:backend" ]]; then
  backendAILogs

elif [[ "$1" == "app:ai:logs:frontend" ]]; then
  frontendAILogs

elif [[ "$1" == "app:ai:list" ]]; then
  llmAIList

elif [[ "$1" == "app:debug" ]]; then
  debugSSHCheck "$@"
  debugDNSCheck "$@"
  debugProxyCheck "$@"

elif [[ "$1" == "app:debug:network" ]]; then
  debugNetwork

elif [[ "$1" == "app:dns:check" ]]; then
  dnsCheck

elif [[ "$1" == "app:dns:logs" ]]; then
  dnsLogs;

elif [[ "$1" == "app:domain" ]]; then
  domain "$@"  

elif [[ "$1" == "app:ide:install" ]]; then
  installIDE

elif [[ "$1" == "app:ide:uninstall" ]]; then
  d

elif [[ "$1" == "app:ide:start" ]]; then
  d

elif [[ "$1" == "app:ide:stop" ]]; then
  d 

elif [[ "$1" == "app:container:names" ]]; then
  containersNames

elif [[ "$1" == "app:container:stopped" ]]; then
  containersStopped

elif [[ "$1" == "app:proxy:check" ]]; then
  proxyCheck

elif [[ "$1" == "app:proxy:logs" ]]; then
  proxyLogs

elif [[ "$1" == "app:purge" ]]; then
  bash "$config_dir/stop.sh" "$config_dir"
  dnsDisable
  containerPurge

elif [[ "$1" == "app:stats" ]]; then
  systemStats

elif [[ "$1" == "app:start" ]]; then
  dnsEnable
  bash "$config_dir/start.sh" "$config_dir"

elif [[ "$1" == "app:stop" ]]; then
  bash "$config_dir/stop.sh" "$config_dir"
  dnsDisable

elif [[ "$1" == "app:update" ]]; then
  updateOS
  updateApp "$app_dir" 

elif [[ "$1" == "build:containers" ]]; then
   $app_dir/appcli cli:build:containers

elif [[ "$1" == "build:certificates" ]]; then
   $app_dir/appcli cli:build:certificates

elif [[ "$1" == "config" ]]; then
  $app_dir/appcli cli:site:config $2

elif [[ "$1" == "config:find" ]]; then
  $app_dir/appcli cli:site:config:find $2 $3

elif [ "$1" == "config:remove" ]; then
 
  $app_dir/appcli cli:site:config:remove $2

elif [ "$1" == "config:replace" ]; then
  $app_dir/appcli cli:site:config:replace $2 $3 $4  

elif [ "$1" == "config:update" ]; then
  $app_dir/appcli cli:site:config:update  $2 $3 $4

elif [ "$1" == "create" ]; then
  $app_dir/appcli cli:site:creation $2

elif [[ "$1" == "domains:list" ]]; then
  $app_dir/appcli cli:site:domains:list $2

elif [[ "$1" == "domains:list:users" ]]; then
  $app_dir/appcli cli:site:domains:list:users $2

elif [[ "$1" == "domains:list:search" ]]; then
  $app_dir/appcli cli:site:domains:list:search $2

elif [[ "$1" == "json" ]]; then
  $2

else
  help

fi
